# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callback <- function(name, fun_payload) {
    .Call('RcppActiveBinding_callback', PACKAGE = 'RcppActiveBinding', name, fun_payload)
}

test_create_environment <- function(names, parent, xform) {
    .Call('RcppActiveBinding_test_create_environment', PACKAGE = 'RcppActiveBinding', names, parent, xform)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RcppActiveBinding_RcppExport_registerCCallable', PACKAGE = 'RcppActiveBinding')
})
