# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Enable internal logging
#'
#' Log entries, depending on the log level, will be printed to the standard
#' error stream.
#'
#' @param log_level A character value, one of "WARN", "INFO", "DEBUG", "VERB",
#'   or "NONE".
#'
#' @keywords internal
init_logging <- function(log_level) {
    invisible(.Call('bindrcpp_init_logging', PACKAGE = 'bindrcpp', log_level))
}

callback_string <- function(name, arg) {
    .Call('bindrcpp_callback_string', PACKAGE = 'bindrcpp', name, arg)
}

callback_symbol <- function(name, arg) {
    .Call('bindrcpp_callback_symbol', PACKAGE = 'bindrcpp', name, arg)
}

do_test_create_environment <- function(names, xform, parent) {
    .Call('bindrcpp_do_test_create_environment', PACKAGE = 'bindrcpp', names, xform, parent)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('bindrcpp_RcppExport_registerCCallable', PACKAGE = 'bindrcpp')
})
